trigger:
- none

pool:
  vmImage: windows-latest

stages:
  - stage:
    jobs:
      - job:
        steps:
          - task: SonarQubePrepare@5
            inputs:
              scannerMode: 'MSBuild'
              projectKey: 'Teste-yaml-Sonar'
              projectName: 'Teste - Sonar'
          - task: SonarQubePublish@5
            inputs:
              pollingTimeoutSec: '300'

          - task: SonarQubeAnalyze@5
            inputs:
              jdkversion: 'JAVA_HOME_11_X64'
          
          - task: CopyFiles@2
            inputs:
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'