trigger:
- none

pool:
  vmImage: windows-latest

stages:
  - stage: DeployDev 
    jobs:
      - job: DeployDev
        steps:
          - script: echo "Iniciando Deploy de Dev"
            displayName: 'Deploy Dev'
  
  - stage: DeployQa
    jobs:
      - job: DeployQa
        steps:
          - script: echo "Iniciando Deploy de Qa"
            displayName: 'Deploy Qa'
  
  - stage: DeployProd
    jobs:
      - job: DeployProd
        steps:
          - script: echo "Iniciando Deploy de PROD"
            displayName: 'Deploy PROD'




