trigger:
- none

pool:
  vmImage: windows-latest

stages:
  - stage:
    jobs:
      - job:
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'sonarcloud'
              organization: 'ynocce'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'test-My-Pipelines-Yaml'
              cliProjectName: 'My-Pipelines-Yaml'
              cliSources: '.'
          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'
          - task: SonarCloudAnalyze@1
            inputs:
              jdkversion: 'JAVA_HOME_17_X64'
          